// boilerplate HTTP setup code generated by AWS with modifications for the app

const {AWS} = require("aws-sdk");
const { SNSClient, CreatePlatformEndpointCommand } = require("@aws-sdk/client-sns");

const client = new SNSClient({region: "eu-west-1"})
const snsPlatformAppArn = "arn:aws:sns:eu-west-1:726018912366:app/GCM/MyAllergyAssistant";
exports.handler = async (event, context) => {
    let body;
    let deviceEndpoint;
    let token = event.token;
    let statusCode = '200';
    const headers = {
        'Content-Type': 'application/json',
    };

    try {
        switch (event.httpMethod) {
            case 'POST':
                const res = await client.send(new CreatePlatformEndpointCommand({PlatformApplicationArn: snsPlatformAppArn, Token: token}));
                deviceEndpoint = res.EndpointArn;
                break;
            default:
                throw new Error(`Unsupported method "${event.httpMethod}"`);
        }
    } catch (err) {
        statusCode = '400';
        console.log(err)
        body = err.message;
    } finally {
        body = JSON.stringify(body);
    }

    return {
        statusCode,
        body,
        headers,
        deviceEndpoint
    };
};
