image: node:latest

stages:
  - mobile-build
  - ui-test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - src/frontend/node_modules/

mobile-build:
  stage: mobile-build
  before_script:
    - cd src/frontend
  script:
    - npm install

ui-test:
  stage: ui-test
  before_script:
    - cd src/frontend
  script:
    - npm test
