image: node:latest

stages:
  - mobile-build
  - amplify
  - backend-test
  - ui-test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - src/frontend/node_modules/
    - src/frontend/aws-exports.ts

mobile-build:
  stage: mobile-build
  before_script:
    - cd src/frontend
  script:
    - npm install

amplify:
  stage: amplify
  before_script:
    - cd src
  script:
    - npm install -g @aws-amplify/cli
    - chmod +x ./amplify-gitlab-ci.sh
    - ./amplify-gitlab-ci.sh
    - mv aws-exports.js frontend/aws-exports.ts

backend-test:
  stage: backend-test
  before_script:
    - cd src/backend/lambda_functions
    - ./npm_install.sh
    - cd ../__tests__
    - npm i
  script:
    - npm test

ui-test:
  stage: ui-test
  before_script:
    - cd src/frontend
  script:
    - npm test