image: node:latest

stages:
  - mobile-build
  - amplify
  - ui-test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - src/frontend/node_modules/
    - src/frontend/aws-exports.ts
    - src/amplify/

mobile-build:
  stage: mobile-build
  before_script:
    - cd src/frontend
  script:
    - npm install

amplify:
  stage: amplify
  before_script:
    - cd src
  script:
    - npm install -g @aws-amplify/cli
    - chmod +x ./amplify-gitlab-ci.sh
    - ./amplify-gitlab-ci.sh
    - mv aws-exports.js frontend/aws-exports.ts

ui-test:
  stage: ui-test
  before_script:
    - cd src/frontend
  script:
    - npm test
