image: node:latest

stages:
  - mobile-build
  - ui-test

mobile-build:
  stage: mobile-build
  before_script:
    - cd src/frontend
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

ui-test:
  stage: ui-test
  needs:
    - job: mobile-build
      artifacts: true
  before_script:
    - cd src/frontend
  script:
    - npm test
